### ISSUE TITLE
Out of view pages continue handling SQL connections

### ISSUE THREAD

**Issue by HUSKI3** [TeamSoos/Shampoo#21]
Pages that aren't unloaded "TablesView" have dispatchers running regardless of the page visibility. These should be destroyed when the page is out of view, and respawn when the page is in view again.

**Comment by HUSKI3** [comment]
Bad comment. Reported for harassment of old people

**Comment by RocKing1001** [comment]
ok there old guy

**Comment by RocKing1001** [comment]
#22 @HUSKI3 use the new OnLoad and OnUnload functions to stop the sql connections
